server:
  port: 8091

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sleuth:
    sampler:
      probability: 1.0
logging:
  config: classpath:logback-spring-dev.xml
