

server:
  port: 8082
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  config: classpath:log4j2-spring.xml
#config: cloud/nacos-consumer/log4j2-spring.xml