
spring:
  application:
    name: spring-gateway
  rabbitmq:
    host: ${RABBIT_MQ_HOST:114.117.195.146}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:admin}
    password: ${RABBIT_MQ_PASSWORD:admin123}
  redis:
    host: ${REDIS_HOST:114.117.195.146}
    port: ${REDIS_PORT:6378}
    password: ${REDIS_PASSWORD:redis@Wlz2021}
    lettuce:
      pool:
        max-active: 300

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          # 忽略大小写匹配，默认为 false。
          # 当 eureka 自动大写 serviceId 时很有用。 所以 MYSERIVCE，会匹配 /myservice/**
          lowerCaseServiceId: true
      default-filters:
        - name: Retry
          args:
            retries: 1
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
#      routes:
#          # 路由的ID，没有固定规则，但要求唯一，建议配合服务名
#        - id: payment_routh
#          # 匹配后提供服务的路由地址
#          uri: http://localhost:8080/test
#          # 断言，路径相匹配的进行路由
#          predicates:
#          - Path=/aaa/**


feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.springboot.cloud
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:114.117.195.146}
      port: ${REDIS_PORT:6378}
      password: ${REDIS_PASSWORD:redis@Wlz2021}

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  config: classpath:logback-spring-dev.xml

